### ISSUE TITLE
Unknown authentication strategy "oidc"

### ISSUE THREAD

**Issue by rrubio** [oktadeveloper/okta-nodejs-login-example#4]
Thank you for creating the demo app. I've followed instructions on the README and getting the following error. Any ideas why this is happening?

![image](https://user-images.githubusercontent.com/4221574/106598049-5718fb00-65ab-11eb-83ea-32054db4590b.png)

The following error appears on "npm start" 

![image](https://user-images.githubusercontent.com/4221574/106598335-b24aed80-65ab-11eb-8aa8-28e4b725a810.png)

Cheers, Rodrigo

**Comment by mraible** [comment]
Please see this repo's [blog post](https://developer.okta.com/blog/2020/06/16/nodejs-login) and re-open this issue if that doesn't help.
